server:
  port: 80


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: aixl
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/neuropsychoogical_cognition?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    default-property-inclusion: non_null

  redis:
    #Redis服务器地址
    host: localhost
    #Redis服务器端口号
    port: 6379
    #数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8000
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池吃最大空闲连接
        max-idle: 20
        #连接池最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 5000



mybatis:
#  mapper-locations: classpath:com/aixl/m/dao/mapper/*.xml
  type-aliases-package: com.aixl.m.model
  mapper-locations: classpath:mapper/*.xml


