server:
 # port: 80
  port: 88  #服务器使用
#  tomcat:
#    #设置传输数据大小为无限制
#    max-connections: 50000 #最大连接数
#    max-http-form-post-size: -1 #post方式数据大小设置
#    max-threads: 500   #最大线程数
  #将tomcat替换为undertow
  undertow:
    direct-buffers: true
    io-threads: 4
    worker-threads: 160
    max-http-post-size: -1
    max-cookies: 500
    max-headers: 5000



spring:
  freemarker:
    #禁用检测templates文件
    check-template-location: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: aixl
    druid:
      # 初始化连接大小
      initial-size: 8
      # 最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 64
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      # 配置获取连接等待超时的时间
      max-wait: 60000
      ##配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ##配置一个连接在池中最小生存的时间，单位是毫秒
      min-victable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-open-prepared-statements: 300
      verify-server-certificate: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-dataSource-stat: true
#      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/neuropsychoogical_cognition?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      #url: jdbc:mysql://122.112.225.219:3306/neuropsychoogical_cognition?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: xlrz
      password: Aixl.Hgpsyxlrz2020!
#      initial-size: 10
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  redis:
    #Redis服务器地址
    host: localhost
    #Redis服务器端口号
    port: 6379
    #数据库索引（默认为0）
    database: 0
    #2.0后jedis需要改为lettuce
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
#    jedis:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 8
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 3000
#        #连接池最大空闲连接
#        max-idle: 20
#        #连接池最小空闲连接
#        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 5000
    #password: 123456

  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
      force-response: true
      force-request: true


  #设置post传输大小无限制
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
#  mapper-locations: classpath:com/aixl/m/dao/mapper/*.xml
  type-aliases-package: com.aixl.m.model
  mapper-locations: classpath:mapper/*.xml


#配置分页插件

pagehelper:
  helper-dialect: mysql
  reasonable: false
  page-size-zero: true
#logging:
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} %logger{15} - %msg%n'
#    file: '%d{yyyy-MM-dd HH:mm:ss} %logger{15} - %msg%n'
#  file:
#    clean-history-on-start: false
#  level: error
